import type { ItemCategory } from "./types";

export const sampleLocations = [
  "Bangkok, Thailand",
  "Tokyo, Japan",
  "Seoul, South Korea",
  "Singapore",
  "Hong Kong",
  "Bali, Indonesia",
  "Hanoi, Vietnam",
  "Kuala Lumpur, Malaysia",
  "Manila, Philippines",
  "Taipei, Taiwan",
  "Shanghai, China",
  "Mumbai, India",
  "Dubai, UAE",
  "Istanbul, Turkey",
  "Cairo, Egypt",
];

export const categorizedSampleItems: Record<ItemCategory, string[]> = {
  food: [
    "Street food Pad Thai",
    "Local restaurant meal",
    "Street food noodles",
    "Fresh fruit smoothie",
    "Local beer",
    "Street food dumplings",
    "Local dessert",
    "Street food skewers",
    "Local coffee",
    "Street food rice dish",
  ],
  accommodation: [
    "Budget hostel",
    "Mid-range hotel",
    "Luxury hotel",
    "Guesthouse",
    "Airbnb apartment",
    "Boutique hotel",
    "Resort",
    "Capsule hotel",
    "Homestay",
    "Serviced apartment",
  ],
  transportation: [
    "Local bus ride",
    "Metro/subway ride",
    "Taxi ride (5km)",
    "Tuk-tuk ride",
    "Motorbike rental (per day)",
    "Bicycle rental (per day)",
    "Airport transfer",
    "Intercity bus",
    "Train ticket",
    "Ferry ride",
  ],
  activities: [
    "Museum entrance",
    "Temple visit",
    "City tour",
    "Cooking class",
    "Massage (1 hour)",
    "Yoga class",
    "Boat tour",
    "National park entrance",
    "Cultural show",
    "Adventure activity",
  ],
  shopping: [
    "Local market souvenir",
    "Shopping mall item",
    "Street market clothing",
    "Local handicraft",
    "Electronics item",
    "Local art piece",
    "Traditional clothing",
    "Local jewelry",
    "Street market bag",
    "Local spices",
  ],
};

export const allSampleItems = Object.values(categorizedSampleItems).flat(); 